# Generated by Django 2.0.2 on 2018-04-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictresult',
            name='image',
            field=models.TextField(),
        ),
    ]
