# Generated by Django 2.0.2 on 2018-04-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_auto_20180411_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictresult',
            name='correct',
            field=models.BooleanField(default=True),
        ),
    ]
